# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

r1 = Race.create(name: "Human", image_link: "https://www.nicepng.com/png/detail/79-797443_these-were-the-stories-of-a-restless-people.png")
r2 = Race.create(name: "Halfling", image_link: "https://p.kindpng.com/picc/s/424-4249609_female-lightfoot-halfling-rogue-hd-png-download.png")
r3 = Race.create(name: "Elf", image_link: "https://www.uokpl.rs/fpng/f/426-4263258_elf-png-image.png")
r4 = Race.create(name: "Goblin", image_link: "https://www.pngfind.com/pngs/m/16-169424_view-samegoogleiqdbsaucenao-600px-goblin-goblin-png-transparent-png.png")
r5 = Race.create(name: "Dark Elf", image_link: "https://i7.pngguru.com/preview/945/430/363/dungeons-dragons-elf-dark-elves-in-fiction-character-drow-elf.jpg")
r6 = Race.create(name: "Dwarf", image_link: "https://www.pngfind.com/pngs/m/127-1271242_dwarf-transparent-image-dwarf-male-fighter-d-d.png")
r7 = Race.create(name: "Orc", image_link: "https://www.pngfind.com/pngs/m/128-1289765_orc-png-transparent-image-orc-dnd-png-download.png")
r8 = Race.create(name: "Wizard", image_link: "https://www.nicepng.com/png/detail/16-164091_d-d-beyond-dungeons-and-dragons-wizard.png")

Character.create(race_id: r2.id, character_race: r2.name, name: 'Bilbo Baggins', age: '111', affiliation: 'Thorin and Company', appearance: 'Bilbo is a hobbit from the Shire, a small, out-of-the-way place in Middle-Earth. He is in his prime of life at the age of 50. He is small in height, with large hairy feet and curly hair. As a hobbit he appreciates a good pint, his pipe, and the comforts of home; travel and adventure were not things he took part in.', personality: 'Cleverness, courage, and compassion are all character traits Bilbo possesses. He is humble, yet unafraid to speak his mind. For instance, when Thorin wanted to withhold all of the treasure from the Lakemen and the Elves, Bilbo used his wits and delivered the Arkenstone to the “other side”.', background: 'Bilbo Baggins was born on September 22 by Shire Reckoning (around September 12-14 of our calendar), in the year 2890 of the Third Age. He was the only son of Bungo Baggins and Belladonna Took. In Hobbiton, Bungo Baggins constructed a spacious and luxurious Hobbit-hole for Belladonna, which they named Bag End.')
Character.create(race_id: r2.id, character_race: r2.name, name: 'Frodo Baggins', age: '50', affiliation: 'Fellowship of the Ring', appearance: 'A stout fellow with red cheeks, taller than some (hobbits), and fairer than most", with a cleft chin, a bright eye, and a perky personality', personality: 'As the Ring-bearer and then principal protagonist of The Lord of the Rings, Frodo is endowed with a temperament well suited to resist evil. He is brave, selfless, thoughtful, wise, observant, and even unfailingly polite.', background: "Much of Frodo's youth was spent at Brandy Hall in Buckland, the ancestral home of the Brandybuck family, including his mother (Primula Brandybuck). Frodo was known as something of a rascal, befriending Meriadoc (Merry) Brandybuck and Peregrin (Pippin) Took and causing trouble wherever they went. They would often steal mushrooms from Farmer Maggot's farm Bamfurlong")
Character.create(race_id: r3.id, character_race: r3.name, name: 'Legolas', age: '2931', affiliation: 'Fellowship of the Ring', appearance: 'He has long flowing hair, that shines golden in the starlight, and skin that is quite pale and flawless. His body is finely muscled, without being large and brawny, and he has good upper body strength. His movements are indeed very graceful and quick, as you say, almost as if his being is one with his surroundings.', personality: 'Gentle, though sometimes patronizing and pretentious. Legolas is wise and well-read, but he can be immature when it comes to bickering with those who disagree with him—especially Gimli the dwarf.', background: "Legolas was a Sindarin Elf who was part of the Fellowship of the Ring in the Third Age. Son of the Elvenking Thranduil of Mirkwood, Legolas was Mirkwood's prince, a messenger, and a master archer. With his keen eyesight, sensitive hearing, and excellent bowmanship, Legolas was valuable to the Fellowship in their journey across Middle-earth. He was well-known for becoming friends with the dwarf Gimli, despite their long-held differences.")
Character.create(race_id: r8.id, character_race: r8.name, name: 'Gandalf', age: '2019', affiliation: 'Company of the Ring', appearance: 'Gandalf was shorter in stature than the other two; but his long white hair, his sweeping silver beard, and his broad shoulders, made him look like some wise king of ancient legend. In his aged face under great snowy brows his eyes were set like coals that could suddenly burst into fire.', personality: 'Gandalf is often described in The Lord of the Rings as quick to anger, and equally quick to laugh. His deep wisdom clearly derived from the patience he learned in Valinor, just as his care for all creatures of good will must have come from his strong sense of pity for the weak.', background: 'As a wizard and the bearer of a Ring of Power, Gandalf has great power, but works mostly by encouraging and persuading. He sets out as Gandalf the Grey, possessing great knowledge, and travelling continually, always focused on the mission to counter the Dark Lord Sauron. He is associated with fire, his ring being Narya, the Ring of Fire, and he both delights in fireworks to entertain the hobbits of the Shire, and in great need uses fire as a weapon. As one of the Maiar he is an immortal spirit, but being in a physical body on Middle-earth, he can be killed in battle, as he is by the Balrog from Moria. He is sent back to Middle-earth to complete his mission, now as Gandalf the White and leader of the Istari.')
Character.create(race_id: r8.id, character_race: r8.name, name: 'Saruman', age: '2019', affiliation: 'White Council', appearance: 'In appearance, Saruman was as an old man with black hair. At the end of the Third Age, his hair and beard had turned mostly white — he had only black hairs about his lips and ears. He was tall, his face was long, and his eyes were deep and dark. He would appear in a white cloak, a habit he later changed into a cloak that changed colours as he moved.', personality: 'Commanding, cunning, and immensely powerful. Saruman wasn’t born evil; he initially used his intelligence and power to promote peace. And even after being corrupted by dark magic, Saruman is no cackling, maniacal villain. Instead he uses his regal presence and shrewd tactical mind to meticulously plot the downfall of Middle Earth.', background: 'A devious White Wizard. Though he was once the righteous leader of the Wizards of Middle Earth, Saruman couldn’t resist the great power of dark magic. Now he merely pretends to be a force of good in the world, while secretly plotting to help evil Lord Sauron return to power and take over Middle Earth by leading an Orc army for Sauron’s war.')
Character.create(race_id: r7.id, character_race: r7.name, name: 'Azog', age: '32', affiliation: 'Moria Orcs', appearance: 'He is a white-skinned Orc, known as the Pale Orc or Azog the Defiler. According to Balin, he is from Gundabad. In the movie, the Battle of Azanulbizar appears in a flashback. Thrór is still alive at this time and is beheaded by Azog during the battle.', personality: 'The wrathful, psychopathic, iron-fisted, malevolent, bloodthirsty, insidious, cynical, bitter, malicious, arrogant, and merciless chieftain of the orcs of Moria and leader of the warg riders.', background: 'Azog was an Orc-chieftain of Moria, who started the War of the Dwarves and Orcs when he slew Thrór. He was himself slain by Dáin II Ironfoot in the Battle of Azanulbizar, and was succeeded by his son Bolg.')
Character.create(race_id: r1.id, character_race: r1.name, name: 'Aragorn', age: '87', affiliation: 'Fellowship of the Ring', appearance: 'Lean, dark, tall, with a shaggy head of dark hair flecked with grey, and in a pale stern face a pair of keen grey eyes', personality: 'A quiet, almost brooding individual, Aragorn seeks only the company of a select few people who he can trust, a telltale sign of an Advocate personality. He is passionate and loves deeply; however, very few witness any overt displays of affection from the guarded and secretive warrior.', background: 'Aragorn was the son of Arathorn II and his wife Gilraen. Through his ancestors Isildur and Anarion, the sons of Elendil, whom he closely resembled, he was directly in line for the thrones of both Gondor and Arnor. When he was two years old, his father was killed while pursuing orcs.')
